# Train Test Split

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Boston.csv")
dataset.head(3)

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7

In [8]:
dataset.shape

(506, 15)

In [4]:
input_data = dataset.iloc[:,:-1]
output_data = dataset["medv"]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.25)

In [7]:
x_train

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
456,457,4.66883,0.0,18.10,0,0.7130,5.976,87.9,2.5806,24,666,20.2,10.48,19.01
479,480,14.33370,0.0,18.10,0,0.6140,6.229,88.0,1.9512,24,666,20.2,383.32,13.11
282,283,0.06129,20.0,3.33,1,0.4429,7.645,49.7,5.2119,5,216,14.9,377.07,3.01
320,321,0.16760,0.0,7.38,0,0.4930,6.426,52.3,4.5404,5,287,19.6,396.90,7.20
493,494,0.17331,0.0,9.69,0,0.5850,5.707,54.0,2.3817,6,391,19.2,396.90,12.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,238,0.51183,0.0,6.20,0,0.5070,7.358,71.6,4.1480,8,307,17.4,390.07,4.73
246,247,0.33983,22.0,5.86,0,0.4310,6.108,34.9,8.0555,7,330,19.1,390.18,9.16
201,202,0.03445,82.5,2.03,0,0.4150,6.162,38.4,6.2700,2,348,14.7,393.77,7.43
58,59,0.15445,25.0,5.13,0,0.4530,6.145,29.2,7.8148,8,284,19.7,390.68,6.86
387,388,22.59710,0.0,18.10,0,0.7000,5.000,89.5,1.5184,24,666,20.2,396.90,31.99

In [11]:
x_train.shape , y_train.shape

((379, 14), (379,))

In [12]:
x_test.shape , y_test.shape

((127, 14), (127,))